In [1]:
import pandas as pd
import sqlite3

# 1. Load your cleaned dataset
df = pd.read_csv("cleaned_superstore.csv")   # file should be in the same folder as notebook
print("Dataset loaded. Shape:", df.shape)
print("Columns:", df.columns.tolist())

# 2. Create in-memory SQLite DB
conn = sqlite3.connect(":memory:")

# 3. Load dataframe into SQL table
df.to_sql("sales", conn, index=False, if_exists="replace")
print("Table 'sales' created in SQLite memory database.")

# 4. Define queries
queries = {
    "Profit margin by category": """
        SELECT Category, SUM(Profit)*1.0 / SUM(Sales) AS ProfitMargin
        FROM sales
        GROUP BY Category;
    """,
    "Profit margin by region": """
        SELECT Region, SUM(Profit)*1.0 / SUM(Sales) AS ProfitMargin
        FROM sales
        GROUP BY Region;
    """,
    "Top 5 profit-draining subcategories": """
        SELECT "Sub-Category", SUM(Profit) AS TotalProfit
        FROM sales
        GROUP BY "Sub-Category"
        ORDER BY TotalProfit ASC
        LIMIT 5;
    """,
    "Sales & profit by year": """
        SELECT Year, SUM(Sales) AS TotalSales, SUM(Profit) AS TotalProfit
        FROM sales
        GROUP BY Year
        ORDER BY Year;
    """,
    "Sales by customer segment": """
        SELECT Segment, SUM(Sales) AS TotalSales, SUM(Profit) AS TotalProfit
        FROM sales
        GROUP BY Segment;
    """
}

# 5. Run queries and display results
for title, query in queries.items():
    print(f"\n--- {title} ---")
    result = pd.read_sql(query, conn)
    print(result)

Dataset loaded. Shape: (100, 16)
Columns: ['Order ID', 'Order Date', 'Region', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Profit', 'Quantity', 'Discount', 'Customer Name', 'Segment', 'Ship Mode', 'Year', 'Month', 'Quarter']
Table 'sales' created in SQLite memory database.

--- Profit margin by category ---
          Category  ProfitMargin
0        Furniture      0.054224
1  Office Supplies      0.035577
2       Technology      0.074452

--- Profit margin by region ---
    Region  ProfitMargin
0  Central      0.059973
1     East      0.078688
2    South      0.057713
3     West      0.036685

--- Top 5 profit-draining subcategories ---
  Sub-Category  TotalProfit
0      Binders       -89.47
1       Labels        31.30
2       Tables       106.72
3  Accessories       154.13
4      Storage       184.34

--- Sales & profit by year ---
   Year  TotalSales  TotalProfit
0  2023    90472.07       5085.1

--- Sales by customer segment ---
       Segment  TotalSales  TotalProfit
0     Consumer    38111.61      1724.82
1    Corporate    28707.67      1735.29
2  Home Office    23652.79      1624.99

In [2]:
pd.read_sql("""
    SELECT Category, SUM(Sales) AS TotalSales
    FROM sales
    GROUP BY Category
    ORDER BY TotalSales DESC;
""", conn)

          Category  TotalSales
0        Furniture    33080.66
1       Technology    32141.69
2  Office Supplies    25249.72